kind: APIManager
apiVersion: apps.3scale.net/v1alpha1
metadata:
  name: apimanager-sample
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  externalComponents:
    backend:
      redis: false
    system:
      database: true
      redis: false
    zync:
      database: true
  tenantName: nprd
  wildcardDomain: apps.cluster-htbqk.htbqk.sandbox2689.opentlc.com